Repository gazebosim/ros_gz, pull requests merged in 2020-06, with the labels that each got.

#74 [dashing] Workflow updates
  .github/CODEOWNERS
  .github/workflows/triage.yml
Labels: ros2

#80 Added ros_ign_gazebo for ros2
  .travis/build
  ros_ign_gazebo/CMakeLists.txt
  ros_ign_gazebo/README.md
  ros_ign_gazebo/launch/ign_gazebo.launch.py
  ros_ign_gazebo/package.xml
  ros_ign_gazebo/src/create.cpp
Labels: enhancement

#81 Added ros_ign_gazebo to ros_ign package.xml
  ros_ign/package.xml
Labels: enhancement

#84 Avoid the use of --ros-args arguments outside ros
  ros_ign_image/src/image_bridge.cpp
Labels: bug

#89 [ros2] Fixed CI - Added Foxy
  .travis.yml
  .travis/build
  README.md
  ros_ign_bridge/include/ros_ign_bridge/factory.hpp
  ros_ign_gazebo/src/create.cpp
Labels: enhancement
